spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: com.kevvlvl.financedatasvc.serializer.StockSerializer

logging:
  level:
    ROOT:
      info

server:
  port: 8090